name: Test action

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: run code
        id: run_code
        run: |
          java -jar target/github-actions-check-1.0.0-jar-with-dependencies.jar >> $GITHUB_OUTPUT
      - name: display result
        run: |
          echo ${{ steps.run_code.outputs.result }}
          echo ${{ steps.run_code.outputs.result2 }}