name: Test action

on:
  issues:
    types: [ opened ]

jobs:
  build:
    if: startsWith(github.event.issue.title, 'new') || startsWith(github.event.issue.title, 'fill')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Run code
        id: run_code
        env:
          EMPTY_CELLS_AMOUNT: ${{ vars.EMPTY_CELLS_AMOUNT }}
        run: |
          cp target/github-actions-check-1.0.0-jar-with-dependencies.jar runner.jar
          java -jar runner.jar ${{ github.event.issue.title }} ${{ github.event.issue.author.login }} >> $GITHUB_OUTPUT
      - name: Display result
        run: |
          echo ${{ steps.run_code.outputs.status }}
          echo "${{ steps.run_code.outputs.reason }}"
      - name: Commit & push changes
        if: ${{ steps.run_code.outputs.status }} == 'EXECUTED'
        run: |
          git config user.email "ye.vasyliev@gmail.com"
          git config user.name "Sudoku job"
          [[ "${{ steps.run_code.outputs.status }}" = "EXECUTED" ]] && git add README.md && git commit -m "Update README.md" && git push && echo "CLOSING_REASON=completed" >> $GITHUB_ENV || echo "CLOSING_REASON=not planned" >> $GITHUB_ENV
      - name: Handle result
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue close "${{ github.event.issue.number }}" -c "${{ steps.run_code.outputs.reason }}" -r "${{ env.CLOSING_REASON }}"