name: Test action

on:
  issues:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: run code
        id: run_code
        run: |
          cp target/github-actions-check-1.0.0-jar-with-dependencies.jar github-actions-check-1.0.0-jar-with-dependencies.jar
          java -jar github-actions-check-1.0.0-jar-with-dependencies.jar ${{ github.event.issue.title }} >> $GITHUB_OUTPUT
      - name: display result
        run: |
          echo ${{ steps.run_code.outputs.status }}
          echo ${{ steps.run_code.outputs.reason }}
      - name: Commit & Push changes
        #        uses: actions-js/push@master
        if: ${{ steps.run_code.outputs.status }} == 'EXECUTED'
        #        with:
        #          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git config user.name "Sudoku job"
          git commit -m "Update README.md"
          git push
      - name: set completed reason
        if: ${{ steps.run_code.outputs.status }} == 'EXECUTED'
        run: |
          echo "CLOSING_REASON=completed" >> $GITHUB_ENV
      - name: set completed reason
        if: ${{ steps.run_code.outputs.status }} != 'EXECUTED'
        run: |
          echo "CLOSING_REASON=not planned" >> $GITHUB_ENV
      - name: handle result
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue close "${{ github.event.issue.number }}" -c "${{ steps.run_code.outputs.reason }}" -r "${{ env.CLOSING_REASON }}"